apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: pko-hello
  namespace: platform-pulumi
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: hetzner-pulumi-platform
spec:
  stack: dev
  programRef:
    name: pko-hello
  backend: file:///tmp
  envRefs:
    PULUMI_CONFIG_PASSPHRASE:
      type: Secret
      secret:
        name: pulumi-kubernetes-operator-env
        key: PULUMI_CONFIG_PASSPHRASE
  destroyOnFinalize: true
  serviceAccountName: pulumi-kubernetes-operator
  workspaceReclaimPolicy: Delete
