environments:
  dev:
    provider: hcloud
    cluster:
      name: dev-eu-1
      region: eu-central
      talosVersion: v1.12.0
      kubernetesVersion: v1.34.0
    network:
      cidr: 10.40.0.0/16
    access:
      mode: restricted-public
      allowedCidrs:
        - 0.0.0.0/0
        - ::/0
    nodePools:
      controlPlane:
        - name: cp
          type: cpx32
          location: nbg1
          architecture: amd64
          count: 3
      workers:
        - name: worker
          type: cpx32
          location: nbg1
          architecture: amd64
          count: 2
    packages:
      clusterBaseline: true
      gitopsControlPlane: true
      secrets: true
      certsDns: true
    gitops:
      repoUrl: https://github.com/skel84/hetzner-pulumi-test.git
      targetRevision: main
      rootPath: gitops/root
